### PR TITLE
Add method chaining

### PR DESCRIPTION
**Pull request by gtrufitt**
Returning `this` in `log` and `error` methods allows chaining and adds prettier plugin to eslint...

### CODE REVIEW

**Comment by gtrufitt** [comment]
Ah, actually prettier in the browser behaves differently to prettier in atom... will take a look!

**Comment by gtrufitt** [comment]
Instead of using format I [added the prettier plugin to eslint](https://github.com/guardian/elk-kinesis-logger/pull/7/commits/ad8f147d3b1f4c555c8c677ed3083ff9a07b0451), that way the prettier stuff is done as part of the linting (and shows up in the editor if you have eslint plugin!). I also added the `--fix` option so things that can be auto fixed will be!

I realised I'm not sure what the process is to release this so lets do that when you're back @akash1810 :)

**Review by akash1810 — APPROVED** [review]
awesome! 👍

**Comment by akash1810** [comment]
> I realised I'm not sure what the process is to release

Should be able to follow [this](https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-the-package) to bump the version number and publish. I think this is best done on master too for simplicity? So maybe merge then publish?

**Comment by gtrufitt** [comment]
Cool! Will do

**Pull request merged**
