### PR TITLE
Version 0.1.0 release

### PR DESCRIPTION
**Pull request by gtrufitt**
Minor release adding method chaining functionality to `log` and `error`.

### CODE REVIEW

**Comment by gtrufitt** [comment]
I seem to have already published this to npm https://www.npmjs.com/package/elk-kinesis-logger

**Comment by gtrufitt** [comment]
Just merged to stay in sync with published version.

**Comment by akash1810** [comment]
token 👍 😄

**Comment by gtrufitt** [comment]
❤️

**Pull request merged**
